#### reshape 연습

In [18]:
import numpy as np

A = np.array([ [ 1, 2, 3, 4 ], 
               [ 10, 20, 30, 40 ],
               [ 100, 200, 300, 400] ])

print(A.shape)

(3, 4)


In [19]:
B = A.reshape(-1, 3)

print(B.shape)
print(B)

(4, 3)
[[  1   2   3]
 [  4  10  20]
 [ 30  40 100]
 [200 300 400]]
(2, 6)
[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]


In [20]:
C = A.reshape(-1, 6)

print(C.shape)
print(C)

(2, 6)
[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]


In [21]:
D = A.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

#### 행렬 iterator 연습

In [17]:
A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ])

print(A, '\n')

# 행렬 A 의 iterator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    
    idx = it.multi_index
    
    print('index = ', idx, ' , type(idx) = ' , type(idx), ' , value = ', A[idx])
    
    it.iternext() 

[[10 20 30 40]
 [50 60 70 80]] 

index =  (0, 0)  , type(idx) =  <class 'tuple'>  , value =  10
index =  (0, 1)  , type(idx) =  <class 'tuple'>  , value =  20
index =  (0, 2)  , type(idx) =  <class 'tuple'>  , value =  30
index =  (0, 3)  , type(idx) =  <class 'tuple'>  , value =  40
index =  (1, 0)  , type(idx) =  <class 'tuple'>  , value =  50
index =  (1, 1)  , type(idx) =  <class 'tuple'>  , value =  60
index =  (1, 2)  , type(idx) =  <class 'tuple'>  , value =  70
index =  (1, 3)  , type(idx) =  <class 'tuple'>  , value =  80


In [3]:
B = np.array([10, 20, 30])  # vector

# 벡터 B 에 대한 iterator

it = np.nditer(B, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    
    idx = it.multi_index
    
    print('current index = ', idx, ' , type(idx) = ' , type(idx), ' , current value = ', B[idx])
    
    it.iternext()

current index =  (0,)  , type(idx) =  <class 'tuple'>  , current value =  10
current index =  (1,)  , type(idx) =  <class 'tuple'>  , current value =  20
current index =  (2,)  , type(idx) =  <class 'tuple'>  , current value =  30


#### [예제 1]

In [4]:
A = np.array([1, 2])
B = np.array([3, 4])
T = np.array([5, 6])

print(A.shape)
print(B.shape)

print((1-A)*A)
print(T*(1-A)*A)

(2,)
(2,)
[ 0 -2]
[  0 -12]


In [5]:
C = np.array([ [2], [3] ])
D = np.array([ [4], [5] ])
T = np.array([ [7], [8] ])

print(C.shape)
print(D.shape)

print((1-C)*C)
print(T*(1-C)*C)

(2, 1)
(2, 1)
[[-2]
 [-6]]
[[-14]
 [-48]]


#### [예제 2]

In [6]:
X = np.array([ [1,2], [3,4] ])
W = np.array([ [0,1,1], [3,2,1] ])
T = np.array([ [1,0], [0,2] ])
b = -1

In [7]:
Y = np.dot(X, W) + b

print(Y)

[[ 5  4  2]
 [11 10  6]]


In [8]:
E = T - Y

print(E)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [9]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])

B = np.array([10, 20, 30])

C = A.T

D = np.dot(C, B)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

#### [예제 3]

In [10]:
X = np.array([ [7, 5, 3, 1], [1, 2, 3, 4], [4, 0, 2, 8] ])

X.shape

(3, 4)

In [11]:
A = X.reshape(-1, 3)

A

array([[7, 5, 3],
       [1, 1, 2],
       [3, 4, 4],
       [0, 2, 8]])

In [12]:
B = A[0:2, 1:2]

B

array([[5],
       [1]])

In [13]:
C = A[1:, :-1]

C

array([[1, 1],
       [3, 4],
       [0, 2]])

In [14]:
D = np.argmax(A, 1)

D

array([0, 2, 1, 2], dtype=int64)

In [15]:
E = C.reshape(-1,6)

E

array([[1, 1, 3, 4, 0, 2]])

In [16]:
F = np.sum(E)

F

11